### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dry1515** [iceland2k14/secp256k1#42]
Traceback (most recent call last):
  File "C:\Users\ms\Desktop\secp256k1-main\1.py", line 1, in <module>
    import secp256k1 as ice
  File "C:\Users\ms\Desktop\secp256k1-main\secp256k1.py", line 22, in <module>
    ice = ctypes.CDLL(pathdll)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ms\AppData\Local\Programs\Python\Python312\Lib\ctypes\__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Could not find module 'C:\Users\ms\Desktop\secp256k1-main\ice_secp256k1.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by arashisec** [comment]
Same with me. Waiting how to fix

**Comment by noidealves** [comment]
Install the Visual C++ Redistributable and your problem will be solved

**Comment by iceland2k14** [comment]
Try with new. If not working let me know

**Comment by arashisec** [comment]
still not work at ARM device

**Comment by iceland2k14** [comment]
ARM not supported. Only Windows and Linux
